name: Deploy to AWS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Gerar Arquivo ZIP do projeto
        run: zip -r deploy.zip . -x "*.git*" # A AWS Beanstalk gosta de arquivos .zip

      - name: Deploy no Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21 # Uma Action pronta e famosa
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          version_label: ${{ github.sha }} # Usa o código do commit como versão
          region: us-east-1
          deployment_package: deploy.zip